version: "3.8"
services:
    api:
        build: ./api
        volumes: 
            - ./api/src:/app/src
        ports:
            - 3000:3000
        environment: 
            DB_URL: mongodb://db/auth-app
    db:
        image: mongo:4.0-xenial
        ports:
            - 27017:27017
        volumes:
            - dbdata:/data/db
            - dbconfig:/data/configdb
volumes:
    dbdata:
    dbconfig: